#!/usr/bin/env python3
"""build_wave3_manifest.py — mint the rid->uid ingest manifest for wave-3.

Reads the five per-report extract YAMLs in corpus/synthesis/wave-3/ and emits
corpus/synthesis/ingest-manifest-wave3.yaml, assigning u-ids sequentially from
--start (default 347, i.e. one past the existing u-0346). The extracts are the
index only; S1 mints from the report's full unit block (see S1-MINTING-RULES).
"""
import argparse
import os
import sys
from datetime import date

try:
    import yaml
except ImportError:
    print("pyyaml required", file=sys.stderr)
    sys.exit(2)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYN = os.path.join(ROOT, "corpus", "synthesis", "wave-3")

REPORTS = [
    ("01-big-history", "corpus/reports/wave-3/01-big-history.md",
     "corpus/synthesis/wave-3/01-extract.yaml"),
    ("02-existential-risk", "corpus/reports/wave-3/02-existential-risk.md",
     "corpus/synthesis/wave-3/02-extract.yaml"),
    ("03-attention-tech", "corpus/reports/wave-3/03-attention-tech.md",
     "corpus/synthesis/wave-3/03-extract.yaml"),
    ("04-secular-meaning", "corpus/reports/wave-3/04-secular-meaning.md",
     "corpus/synthesis/wave-3/04-extract.yaml"),
    ("05-judgement-science", "corpus/reports/wave-3/05-judgement-science.md",
     "corpus/synthesis/wave-3/05-extract.yaml"),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start", type=int, default=347)
    ap.add_argument("--out", default=os.path.join(SYN, "..", "ingest-manifest-wave3.yaml"))
    args = ap.parse_args()

    uid = args.start
    reports_out = []
    total = 0
    for slug, src, extract_rel in REPORTS:
        extract_path = os.path.join(ROOT, extract_rel.replace("/", os.sep))
        with open(extract_path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        units = []
        for u in data["units"]:
            units.append({"rid": u["rid"], "uid": f"u-{uid:04d}"})
            uid += 1
        reports_out.append({
            "report": slug,
            "source": src,
            "extract": extract_rel,
            "count": len(units),
            "units": units,
        })
        total += len(units)

    manifest = {
        "generated": str(date.today()),
        "next_id_before": f"u-{args.start:04d}",
        "next_id_after": f"u-{uid:04d}",
        "total_units": total,
        "reports": reports_out,
    }
    out_path = os.path.join(ROOT, args.out.replace("/", os.sep))
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("# AUTO-GENERATED by tools/build_wave3_manifest.py — rid->uid index for S1.\n")
        yaml.dump(manifest, fh, sort_keys=False, default_flow_style=False, allow_unicode=True)
    print(f"Wrote {out_path}")
    print(f"Reports: {len(reports_out)}  Units: {total}  "
          f"Range: u-{args.start:04d} .. u-{uid-1:04d}  next: u-{uid:04d}")


if __name__ == "__main__":
    main()
