#!/usr/bin/env python3
"""generate_status.py — derive STATE.md's STATUS block mechanically from the store.

The external review (P1-10) showed hand-maintained counts drift into falsehood.
This script computes them and rewrites the delimited block in STATE.md:

    <!-- STATUS:BEGIN (generated by tools/generate_status.py — do not edit by hand) -->
    ...
    <!-- STATUS:END -->

Run after any graph/page-spec change; validators + this script are the gate.
"""
import collections
import datetime
import io
import os
import re
import subprocess
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(sub):
    out = {}
    d = os.path.join(ROOT, "graph", sub)
    for f in sorted(os.listdir(d)):
        if f.endswith(".yaml") and "EXAMPLE" not in f:
            out[os.path.splitext(f)[0]] = yaml.safe_load(open(os.path.join(d, f), encoding="utf-8"))
    return out


def main():
    units, claims, edges = load("units"), load("claims"), load("edges")
    conf = collections.Counter(u.get("attribution_confidence") for u in units.values())
    ver = collections.Counter((u.get("verification") or {}).get("status") for u in units.values())
    cw = collections.Counter(u.get("copyright_flag") for u in units.values())
    care_gate = sum(1 for u in units.values() if str(u.get("notes", "")).startswith("CONSENT GATE"))
    care_stub = sum(1 for u in units.values() if str(u.get("notes", "")).startswith("RECORD-ONLY"))
    cstat = collections.Counter(c.get("status") for c in claims.values())
    etypes = collections.Counter(e.get("type") for e in edges.values())
    def reg_state(name):
        with open(os.path.join(ROOT, "graph", "registries", f"{name}.yaml"), encoding="utf-8") as f:
            entries = yaml.safe_load(f)["entries"]
        canon = {e["canonical_id"] for e in entries if e.get("canonical_id")}
        uncanon = sum(1 for e in entries if not e.get("canonical_id"))
        return len(entries), len(canon), uncanon

    t_raw, t_canon, t_open = reg_state("traditions")
    d_raw, d_canon, d_open = reg_state("domains")
    specs = [f for f in os.listdir(os.path.join(ROOT, "book", "page-specs")) if f.endswith(".yaml")]

    def run(tool):
        r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", tool)],
                           capture_output=True, text=True)
        m = re.search(r"(\d+) error\(s\), (\d+) warning\(s\)", r.stdout)
        return (int(m.group(1)), int(m.group(2))) if m else ("?", "?")

    e1, w1 = run("validate_units.py")
    e2, w2 = run("validate_graph.py")
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True,
                            text=True, cwd=ROOT).stdout.strip()

    def fmt(c):
        return " · ".join(f"{k}: {v}" for k, v in sorted(c.items(), key=lambda x: -x[1]) if k)

    block = f"""<!-- STATUS:BEGIN (generated by tools/generate_status.py — do not edit by hand) -->
**Generated:** {datetime.date.today().isoformat()} from content-state commit `{commit}` (the commit adding this block is its child)

| Store | Count | Breakdown |
|---|---|---|
| units | {len(units)} | attribution — {fmt(conf)} |
| — verification | | {fmt(ver)} |
| — copyright | | {fmt(cw)} |
| — CARE | | consent-gate: {care_gate} · record-only stubs: {care_stub} |
| claims | {len(claims)} | {fmt(cstat)} |
| edges | {len(edges)} | {fmt(etypes)} |
| page-specs | {len(specs)} | |
| taxonomy | | traditions: {t_raw} raw -> {t_canon} canonical ({t_open} unmapped) · domains: {d_raw} raw -> {d_canon} canonical ({d_open} unmapped) |
| validators | | units: {e1} err/{w1} warn · graph: {e2} err/{w2} warn (warnings are counted debt) |
<!-- STATUS:END -->"""

    p = os.path.join(ROOT, "STATE.md")
    t = io.open(p, encoding="utf-8").read()
    if "<!-- STATUS:BEGIN" in t:
        t = re.sub(r"<!-- STATUS:BEGIN.*?STATUS:END -->", block, t, flags=re.S)
    else:
        t = t.replace("## Status snapshot", f"{block}\n\n## Status snapshot", 1)
    io.open(p, "w", encoding="utf-8", newline="\n").write(t)
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
